/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.pong.vapor;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

/**
 *
 * @author Adriane
 */
public class AddFunds extends javax.swing.JDialog {

    /**
     * Creates new form AddFunds
     */
    public AddFunds(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addFundsLabel = new javax.swing.JLabel();
        addFundsField = new javax.swing.JTextField();
        dollarSign = new javax.swing.JLabel();
        addFundsButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        addFundsLabel.setFont(new java.awt.Font("Lato Semibold", 1, 48)); // NOI18N
        addFundsLabel.setForeground(new java.awt.Color(12, 12, 12));
        addFundsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addFundsLabel.setText("Add Funds");

        addFundsField.setFont(new java.awt.Font("Lato Light", 0, 18)); // NOI18N
        addFundsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFundsFieldActionPerformed(evt);
            }
        });

        dollarSign.setFont(new java.awt.Font("Lato Semibold", 1, 48)); // NOI18N
        dollarSign.setForeground(new java.awt.Color(12, 12, 12));
        dollarSign.setText("$");

        addFundsButton.setBackground(new java.awt.Color(0, 51, 153));
        addFundsButton.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        addFundsButton.setForeground(new java.awt.Color(255, 255, 255));
        addFundsButton.setText("Add");
        addFundsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFundsButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(dollarSign)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addFundsField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addFundsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addFundsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addFundsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addFundsField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addFundsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dollarSign))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFundsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFundsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFundsFieldActionPerformed

    private void addFundsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFundsButtonActionPerformed
        Connection conn = null;
        
        try {
            conn = DriverManager.getConnection("jdbc:sqlite:vapordb.db");
            double addedFunds = Double.parseDouble(addFundsField.getText());
            
            if (addedFunds > 500000) {
                JOptionPane.showMessageDialog(null, "Maximum amount is $500,000. Please input a lower amount.", "Error", JOptionPane.WARNING_MESSAGE);
            } else if (addedFunds < 20) {
                JOptionPane.showMessageDialog(null, "Minimum amount is $20. Please input a higher amount.", "Error", JOptionPane.WARNING_MESSAGE);                
            } else {
                // updating the balance to reflect the funds added
                staticVar.userThatIsLoggedIn.balance += addedFunds;
                PreparedStatement st = conn.prepareStatement("UPDATE accounts SET balance=? WHERE account_id=?");
                st.setDouble(1, staticVar.userThatIsLoggedIn.balance);
                st.setInt(2, staticVar.userThatIsLoggedIn.id);
                st.executeUpdate();
                
                Settings.userBalance.setText(String.format("$ %.2f", staticVar.userThatIsLoggedIn.balance));     // automatically updates balance in settings
                JOptionPane.showMessageDialog(null, "Added funds successfully. Your new balance is $" + String.format("%.2f", staticVar.userThatIsLoggedIn.balance), "Success", JOptionPane.PLAIN_MESSAGE);                
            }
            
            conn.close();
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Input is not a valid number.", "Error", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        }
        

    }//GEN-LAST:event_addFundsButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
          dispose();                                  // deletes the current frame
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddFunds dialog = new AddFunds(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFundsButton;
    private javax.swing.JTextField addFundsField;
    private javax.swing.JLabel addFundsLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel dollarSign;
    // End of variables declaration//GEN-END:variables
}
