/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.pong.vapor;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

/**
 *
 * @author Adriane
 */
public class ChangeUsername extends javax.swing.JDialog {

    /**
     * Creates new form ChangeUsername
     */
    public ChangeUsername(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currUsernameLAbel = new javax.swing.JLabel();
        newUsernameLabel = new javax.swing.JLabel();
        confirmNewUsernameLabel = new javax.swing.JLabel();
        currUsernameField = new javax.swing.JTextField();
        newUsernameField = new javax.swing.JTextField();
        confirmNewUsernameField = new javax.swing.JTextField();
        changeUsernameLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        changeUsernameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        currUsernameLAbel.setFont(new java.awt.Font("Lato Semibold", 0, 24)); // NOI18N
        currUsernameLAbel.setText("Current username");

        newUsernameLabel.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        newUsernameLabel.setText("New username");

        confirmNewUsernameLabel.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        confirmNewUsernameLabel.setText("Confirm new username");

        currUsernameField.setFont(new java.awt.Font("Lato Light", 0, 18)); // NOI18N
        currUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currUsernameFieldActionPerformed(evt);
            }
        });

        newUsernameField.setFont(new java.awt.Font("Lato Light", 0, 18)); // NOI18N
        newUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUsernameFieldActionPerformed(evt);
            }
        });

        confirmNewUsernameField.setFont(new java.awt.Font("Lato Light", 0, 18)); // NOI18N
        confirmNewUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmNewUsernameFieldActionPerformed(evt);
            }
        });

        changeUsernameLabel.setFont(new java.awt.Font("Lato Semibold", 1, 36)); // NOI18N
        changeUsernameLabel.setForeground(new java.awt.Color(12, 12, 12));
        changeUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changeUsernameLabel.setText("Change Username");

        backButton.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        changeUsernameButton.setBackground(new java.awt.Color(0, 102, 102));
        changeUsernameButton.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        changeUsernameButton.setForeground(new java.awt.Color(204, 204, 204));
        changeUsernameButton.setText("Change");
        changeUsernameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUsernameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(changeUsernameButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changeUsernameLabel)
                            .addComponent(confirmNewUsernameLabel)
                            .addComponent(currUsernameLAbel)
                            .addComponent(currUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newUsernameLabel)
                            .addComponent(newUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmNewUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 84, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backButton)
                .addGap(5, 5, 5)
                .addComponent(changeUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currUsernameLAbel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(newUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmNewUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmNewUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(changeUsernameButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void currUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currUsernameFieldActionPerformed

    private void newUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newUsernameFieldActionPerformed

    private void confirmNewUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmNewUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmNewUsernameFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();                                  // deletes the current frame
    }//GEN-LAST:event_backButtonActionPerformed

    private void changeUsernameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUsernameButtonActionPerformed
        String inputtedCurrUsername = currUsernameField.getText();
        String inputtedNewUsername = newUsernameField.getText();
        String inputtedConfirmNewUsername = confirmNewUsernameField.getText();
        
        Connection conn = null;
        
        try {
             conn = DriverManager.getConnection("jdbc:sqlite:vapordb.db");
           
            if (inputtedNewUsername.equals("") || inputtedConfirmNewUsername.equals("")) {
                 JOptionPane.showMessageDialog(null, "Inputted username should not be empty.", "Error", JOptionPane.WARNING_MESSAGE);
            }
             
            else if (staticVar.userThatIsLoggedIn.username.equals(inputtedCurrUsername)) {   // checks if inputted username matches the one in database
                if (inputtedNewUsername.equals(inputtedConfirmNewUsername)) {           // checks if both new password inputted matches
                    
                    PreparedStatement st = conn.prepareStatement("SELECT * FROM accounts WHERE username=?");    // checks if username is unique
                    st.setString(1, inputtedConfirmNewUsername);
                    ResultSet rs = st.executeQuery();
                    
                    if (!rs.isBeforeFirst()) {
                        st = conn.prepareStatement("UPDATE accounts SET username=? WHERE account_id=?");
                        st.setString(1, inputtedConfirmNewUsername);
                        st.setInt(2, staticVar.userThatIsLoggedIn.id);
                        st.executeUpdate();
                        
                        staticVar.userThatIsLoggedIn.username = inputtedConfirmNewUsername;
                        Settings.accountName.setText(inputtedConfirmNewUsername);                                           // updates username shown in settings
                        JOptionPane.showMessageDialog(null, "Username updated.", "Success", JOptionPane.PLAIN_MESSAGE);
                        conn.close();
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Username already exists.", "Error", JOptionPane.WARNING_MESSAGE);
                    }
                    
                } else {
                    JOptionPane.showMessageDialog(null, "New usernames do not match.", "Error", JOptionPane.WARNING_MESSAGE);

                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Current username inputted is incorrect.", "Error", JOptionPane.WARNING_MESSAGE);
            }
           
        } catch (Exception e) {
            e.printStackTrace();
        }
        

    }//GEN-LAST:event_changeUsernameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChangeUsername dialog = new ChangeUsername(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton changeUsernameButton;
    private javax.swing.JLabel changeUsernameLabel;
    private javax.swing.JTextField confirmNewUsernameField;
    private javax.swing.JLabel confirmNewUsernameLabel;
    private javax.swing.JTextField currUsernameField;
    private javax.swing.JLabel currUsernameLAbel;
    private javax.swing.JTextField newUsernameField;
    private javax.swing.JLabel newUsernameLabel;
    // End of variables declaration//GEN-END:variables
}
