/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.pong.vapor;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class GamePage extends javax.swing.JDialog {

    /**
     * Creates new form GamePage3
     */
    public GamePage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    // Returns the genre of game shown on GamePage
    static String displayGenre() {
        Connection conn = null;
        try {
            conn = DriverManager.getConnection("jdbc:sqlite:vapordb.db");
            
            ResultSet rs = conn.createStatement().executeQuery("SELECT genre_name FROM game_genres JOIN genres ON game_genres.genre_id=genreS.genre_id WHERE game_id=" + String.valueOf(staticVar.previewedGame.id));
            
            String genreName = rs.getString("genre_name");
            conn.close();
            return "Genre: " + genreName;
            

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return "Genre: NULL"; // in case of null value
    }
    
    // Returns the publisher name of game shown on GamePage
    static String displayDevName() {
        Connection conn = null;
        try {
            conn = DriverManager.getConnection("jdbc:sqlite:vapordb.db");
            
            ResultSet rs = conn.createStatement().executeQuery("SELECT publisher_name FROM games JOIN publishers ON games.developer_id=publishers.publisher_id WHERE game_id=" + String.valueOf(staticVar.previewedGame.id));
            
            String publisherName = rs.getString("publisher_name");
            conn.close();
            return publisherName;
            

        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return "Publisher"; // in case of null value
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameDeveloperName = new javax.swing.JLabel();
        gameName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addToCartButton = new javax.swing.JButton();
        gameGenre = new javax.swing.JLabel();
        gamePopularity2 = new javax.swing.JLabel();
        gameRating = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        gameDeveloperName.setFont(new java.awt.Font("Lato Semibold", 0, 18)); // NOI18N
        gameDeveloperName.setForeground(new java.awt.Color(12, 12, 12));
        gameDeveloperName.setText(displayDevName());
        gameDeveloperName.setToolTipText("");
        gameDeveloperName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        gameName.setBackground(new java.awt.Color(255, 51, 51));
        gameName.setFont(new java.awt.Font("Meiryo", 1, 48)); // NOI18N
        gameName.setForeground(new java.awt.Color(12, 12, 12));
        gameName.setText(staticVar.previewedGame.name);
        gameName.setToolTipText("");
        gameName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setForeground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        addToCartButton.setBackground(new java.awt.Color(0, 153, 153));
        addToCartButton.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        addToCartButton.setText("Add to Cart");
        addToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartButtonActionPerformed(evt);
            }
        });

        gameGenre.setFont(new java.awt.Font("Lato Light", 0, 18)); // NOI18N
        gameGenre.setForeground(new java.awt.Color(12, 12, 12));
        gameGenre.setText(displayGenre());
        gameGenre.setToolTipText("");

        gamePopularity2.setFont(new java.awt.Font("Lato Light", 0, 18)); // NOI18N
        gamePopularity2.setForeground(new java.awt.Color(12, 12, 12));
        gamePopularity2.setText("Popularity: " + String.valueOf(staticVar.previewedGame.popularity));
        gamePopularity2.setToolTipText("");

        gameRating.setFont(new java.awt.Font("Lato Light", 0, 18)); // NOI18N
        gameRating.setForeground(new java.awt.Color(12, 12, 12));
        gameRating.setText("User Rating: " + String.valueOf(staticVar.previewedGame.userRating));
        gameRating.setToolTipText("");

        jEditorPane1.setContentType("text/html"); // NOI18N
        jEditorPane1.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jEditorPane1.setText("<html><div style=\"font-family:Lato;font-size:18px;width:625px;\"" + staticVar.previewedGame.description + "</div></html>");
        jEditorPane1.setCaretPosition(0);
        jEditorPane1.setDisabledTextColor(new java.awt.Color(30, 30, 30));
        jEditorPane1.setEnabled(false);
        jScrollPane2.setViewportView(jEditorPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gameDeveloperName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(510, 510, 510))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gameName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gameGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addToCartButton)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gamePopularity2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gameRating, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(gameName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameDeveloperName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gamePopularity2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameRating, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addToCartButton)
                    .addComponent(gameGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartButtonActionPerformed
        Connection conn = null;
        try {
            conn = DriverManager.getConnection("jdbc:sqlite:vapordb.db");
            
            // checks if the game exists in the library of the user (so that it doesn't buy the same game twice)
            PreparedStatement st = conn.prepareStatement("SELECT account_id FROM ownerships WHERE account_id=? AND game_id=?");
            st.setInt(1, staticVar.userThatIsLoggedIn.id);
            st.setInt(2, staticVar.previewedGame.id);
            ResultSet rs = st.executeQuery();
            
            if (!rs.isBeforeFirst()) {
                addGameToCart();
            } else {
                JOptionPane.showMessageDialog(null, "You already own this game.", "Error", JOptionPane.WARNING_MESSAGE);
            }

            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_addToCartButtonActionPerformed

    static void addGameToCart() {
        boolean gameAlreadyInCart = false;
        
        // loops through the cart to check if game is already in the cart
        for (Game g : staticVar.userCart) {
            if (g.id==staticVar.previewedGame.id)   gameAlreadyInCart = true;
        }
        
        if (!gameAlreadyInCart) {
            staticVar.userCart.add(staticVar.previewedGame);
            JOptionPane.showMessageDialog(null, "Game added to cart.", "Success", JOptionPane.PLAIN_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(null, "Game already in cart.", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GamePage dialog = new GamePage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartButton;
    private javax.swing.JLabel gameDeveloperName;
    private javax.swing.JLabel gameGenre;
    private javax.swing.JLabel gameName;
    private javax.swing.JLabel gamePopularity2;
    private javax.swing.JLabel gameRating;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
